modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId = "delighto_flight"
version = "1.21.1-1.0.0"
displayName = "Delight'o Flight"
credits = "StarOcean(artist),Leo_Lezury(thanks for some help)"
authors = "CloudMeow"
description = '''An addon for Farmer's Delight about sky'''
logoFile = "logo.png"
logoBlur = false

[[mixins]]
config = "delighto_flight.mixins.json"

[[dependencies.delighto_flight]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.66-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.delighto_flight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.delighto_flight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.7,)"
ordering = "AFTER"
side = "BOTH"